name: Docker Image CI/CD Ultrasound Classificator

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          # Replace 'your-docker-image-name' and 'your-image-tag' with appropriate values
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ultrasound-classificator-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ultrasound-classificator-api:latest
